using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace CheryTools
{
    internal static class LocalizationManager
    {
        public const string DefaultLanguage = "Chinese";
        private static readonly string[] _languageIds = new string[] { "Chinese", "English", "Korean" };
        private static readonly Dictionary<string, Dictionary<string, string>> _builtIn = CreateBuiltInLanguages();
        private static Dictionary<string, string> _active = _builtIn[DefaultLanguage];

        public static string ActiveLanguage { get; private set; } = DefaultLanguage;

        public static string[] LanguageIds
        {
            get { return (string[])_languageIds.Clone(); }
        }

        public static string LanguageDirectory
        {
            get
            {
                string root = Main.ModEntry != null ? Main.ModEntry.Path : AppDomain.CurrentDomain.BaseDirectory;
                return Path.Combine(root, "Languages");
            }
        }

        public static void Initialize(string language)
        {
            Reload(language);
        }

        public static void Reload(string language)
        {
            string normalized = NormalizeLanguage(language);
            Dictionary<string, string> merged = new Dictionary<string, string>(_builtIn[DefaultLanguage], StringComparer.OrdinalIgnoreCase);
            if (_builtIn.TryGetValue(normalized, out Dictionary<string, string> builtInLanguage))
            {
                foreach (var pair in builtInLanguage)
                {
                    merged[pair.Key] = pair.Value;
                }
            }

            string filePath = GetLanguageFilePath(normalized);
            if (File.Exists(filePath))
            {
                try
                {
                    Dictionary<string, string> userLanguage = LoadLanguageFile(filePath);
                    foreach (var pair in userLanguage)
                    {
                        merged[pair.Key] = pair.Value;
                    }
                }
                catch (Exception ex)
                {
                    Main.Logger?.Log("[CheryTools] Failed to load language file: " + ex.Message);
                }
            }

            ActiveLanguage = normalized;
            _active = merged;
        }

        public static string T(string key, string fallback)
        {
            if (string.IsNullOrEmpty(key))
            {
                return fallback ?? string.Empty;
            }

            if (_active != null && _active.TryGetValue(key, out string value) && !string.IsNullOrEmpty(value))
            {
                return value;
            }

            if (_builtIn[DefaultLanguage].TryGetValue(key, out string defaultValue) && !string.IsNullOrEmpty(defaultValue))
            {
                return defaultValue;
            }

            return fallback ?? key;
        }

        public static string GetDisplayName(string language)
        {
            string normalized = NormalizeLanguage(language);
            if (_builtIn.TryGetValue(normalized, out Dictionary<string, string> dictionary)
                && dictionary.TryGetValue("meta.displayName", out string displayName)
                && !string.IsNullOrEmpty(displayName))
            {
                return displayName;
            }

            return normalized;
        }

        public static string NormalizeLanguage(string language)
        {
            if (string.IsNullOrEmpty(language))
            {
                return DefaultLanguage;
            }

            for (int i = 0; i < _languageIds.Length; i++)
            {
                if (string.Equals(_languageIds[i], language, StringComparison.OrdinalIgnoreCase))
                {
                    return _languageIds[i];
                }
            }

            return DefaultLanguage;
        }

        public static string CreateMissingLanguageFiles()
        {
            Directory.CreateDirectory(LanguageDirectory);
            for (int i = 0; i < _languageIds.Length; i++)
            {
                string language = _languageIds[i];
                string path = GetLanguageFilePath(language);
                if (!File.Exists(path))
                {
                    File.WriteAllText(path, SerializeLanguage(_builtIn[language]), System.Text.Encoding.UTF8);
                    continue;
                }

                try
                {
                    JObject obj = JObject.Parse(File.ReadAllText(path, System.Text.Encoding.UTF8));
                    HashSet<string> existingKeys = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                    foreach (JProperty property in obj.Properties())
                    {
                        existingKeys.Add(property.Name);
                    }

                    bool changed = false;
                    foreach (var pair in _builtIn[language])
                    {
                        if (existingKeys.Contains(pair.Key))
                        {
                            continue;
                        }

                        obj[pair.Key] = pair.Value;
                        changed = true;
                    }

                    if (changed)
                    {
                        File.WriteAllText(path, obj.ToString(Formatting.Indented), System.Text.Encoding.UTF8);
                    }
                }
                catch (Exception ex)
                {
                    Main.Logger?.Log("[CheryTools] Failed to update language file: " + ex.Message);
                }
            }

            return LanguageDirectory;
        }

        public static string GetLanguageFilePath(string language)
        {
            return Path.Combine(LanguageDirectory, NormalizeLanguage(language) + ".json");
        }

        private static Dictionary<string, string> LoadLanguageFile(string path)
        {
            JObject obj = JObject.Parse(File.ReadAllText(path, System.Text.Encoding.UTF8));
            Dictionary<string, string> result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (JProperty property in obj.Properties())
            {
                if (property.Value == null || property.Value.Type == JTokenType.Null)
                {
                    continue;
                }

                result[property.Name] = property.Value.Type == JTokenType.String
                    ? property.Value.Value<string>()
                    : property.Value.ToString(Formatting.None);
            }

            return result;
        }

        private static string SerializeLanguage(Dictionary<string, string> values)
        {
            JObject obj = new JObject();
            foreach (var pair in values)
            {
                obj[pair.Key] = pair.Value;
            }

            return obj.ToString(Formatting.Indented);
        }

        private static Dictionary<string, Dictionary<string, string>> CreateBuiltInLanguages()
        {
            var languages = new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase);

            languages["Chinese"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "meta.displayName", "Chinese" },
                { "top.tools", "Tools" },
                { "top.keyViewer", "KeyViewer" },
                { "top.overlayer", "Overlayer" },
                { "top.settings", "设置" },
                { "top.help", "帮助" },
                { "window.tools", "Tools" },
                { "window.keyViewer", "KeyViewer" },
                { "window.overlayer", "Overlayer" },
                { "window.help", "帮助" },
                { "window.settings", "设置" },
                { "window.kvEditor", "KV 编辑器" },
                { "tools.tab.optimization", "优化" },
                { "tools.tab.visual", "视觉" },
                { "tools.tab.gameUi", "游戏 UI" },
                { "tools.optimization.title", "优化设置" },
                { "tools.disableAutoplaySpacePause", "禁用自动播放空格暂停" },
                { "tools.disablePlayModeScrollZoom", "禁用播放时滚轮缩放" },
                { "tools.antiBounceKeys", "防弹键" },
                { "tools.antiBounceIntervalMs", "防弹间隔 (ms)" },
                { "tools.antiBounceKeysHelp", "同一个按键两次按下间隔小于 50ms 时忽略第二次输入。" },
                { "tools.visual.title", "视觉" },
                { "tools.hideHitTextEnabled", "启用判定文字隐藏" },
                { "tools.hideAllHitText", "隐藏全部判定文字" },
                { "tools.showAllHitText", "显示全部判定文字" },
                { "tools.customPlanetColors", "启用自定义星球颜色" },
                { "tools.planetColorSettings", "星球颜色设置" },
                { "tools.firePlanet", "火之行星" },
                { "tools.icePlanet", "冰之行星" },
                { "tools.greenPlanet", "？之行星" },
                { "tools.ring", "球环" },
                { "tools.tail", "拖尾" },
                { "tools.gameUi.title", "游戏 UI" },
                { "tools.gameUi.hint", "仅在关卡游玩界面生效，不接管菜单、选关或关卡编辑器 UI。" },
                { "tools.gameUi.enable", "启用游戏 UI 控制" },
                { "tools.gameUi.resetAll", "重置全部" },
                { "tools.gameUi.control", "接管" },
                { "tools.gameUi.visible", "可见" },
                { "tools.gameUi.advancedLocked", "开发者选项未解锁：此项仅支持隐藏，位置/缩放/透明度已禁用。" },
                { "tools.gameUi.positionX", "位置 X" },
                { "tools.gameUi.positionY", "位置 Y" },
                { "tools.gameUi.scale", "缩放" },
                { "tools.gameUi.alpha", "透明度" },
                { "tools.gameUi.resetThis", "重置此项" },
                { "tools.gameUi.target.levelName", "关卡名称" },
                { "tools.gameUi.target.countdown", "倒计时" },
                { "tools.gameUi.target.hitErrorMeter", "准度条" },
                { "tools.gameUi.target.difficultySwitch", "判定模式切换" },
                { "tools.gameUi.target.noFailSwitch", "不会失败模式开关" },
                { "tools.gameUi.target.autoplaySwitch", "自动演奏开关" },
                { "tools.gameUi.target.autoplayText", "自动播放文字" },
                { "tools.gameUi.target.buildWatermark", "测试版本水印" },
                { "tools.inputLimit.title", "按键限制" },
                { "tools.inputLimit.enable", "启用独立按键限制" },
                { "tools.inputLimit.help", "启用后只放行下方登记的按键，最多 30 个；菜单热键、Esc、Ctrl、F10 保底放行。" },
                { "tools.inputLimit.add", "添加限制键" },
                { "tools.inputLimit.waiting", "[等待按键...]" },
                { "tools.inputLimit.clear", "清空限制键" },
                { "common.index", "序号" },
                { "common.key", "按键" },
                { "common.action", "操作" },
                { "common.delete", "删除" },
                { "kv.enable", "开启按键显示悬浮窗" },
                { "kv.onlyShowPlaying", "仅游戏时显示" },
                { "kv.limitInput", "限制输入" },
                { "kv.resetStats", "重置统计数据" },
                { "kv.export", "导出 KV 配置 (.ctkv)" },
                { "kv.import", "导入 KV 配置 (.ctkv)" },
                { "kv.newConfig", "新建配置" },
                { "kv.blankConfig", "空白配置" },
                { "kv.from16kPreset", "从 16K 预设开始" },
                { "kv.from12kPreset", "从 12K 预设开始" },
                { "kv.from10kPreset", "从 10K 预设开始" },
                { "kv.from8kPreset", "从 8K 预设开始" },
                { "kv.noConfig", "还没有 KV 配置" },
                { "kv.createHint", "点击左侧“新建配置”开始。" },
                { "kv.currentConfig", "当前配置" },
                { "kv.name", "名称" },
                { "kv.configEnable", "启用显示" },
                { "kv.showInGame", "游戏中显示" },
                { "kv.nodeCount", "节点数量: {0}" },
                { "kv.openEditor", "打开 FreeMake 编辑器" },
                { "kv.clearNodes", "清空节点" },
                { "kv.copyConfig", "复制配置" },
                { "kv.deleteConfig", "删除配置" },
                { "kv.replaceWithPreset", "用预设覆盖当前配置:" },
                { "kv.emptyPreset", "空白" },
                { "kv.appearanceSettings", "当前配置外观设置" },
                { "kv.section.general", "综合设置" },
                { "kv.section.key", "按键设置" },
                { "kv.section.rain", "雨滴设置" },
                { "kv.section.animation", "动画设置" },
                { "kv.customFontPath", "自定义字体路径 (如 D:/font.ttf 或 .otf)" },
                { "kv.keyTextOffsetX", "配置按键文字X偏移" },
                { "kv.keyTextOffsetY", "配置按键文字Y偏移" },
                { "kv.countTextOffsetX", "配置计数文字X偏移" },
                { "kv.countTextOffsetY", "配置计数文字Y偏移" },
                { "kv.reloadFont", "重新加载字体" },
                { "kv.scale", "缩放大小" },
                { "kv.hideCountText", "隐藏计数数字" },
                { "kv.defaultBorderThickness", "配置默认边框粗细" },
                { "kv.textOutline", "文字描边" },
                { "kv.enableKeyTextOutline", "开启按键文字描边" },
                { "kv.keyTextOutlineColor", "按键文字描边颜色" },
                { "kv.keyTextOutlineThickness", "按键文字描边粗细" },
                { "kv.enableCountTextOutline", "开启计数文字描边" },
                { "kv.countTextOutlineColor", "计数文字描边颜色" },
                { "kv.countTextOutlineThickness", "计数文字描边粗细" },
                { "kv.textShadow", "文字阴影" },
                { "kv.enableKeyTextShadow", "开启按键文字阴影" },
                { "kv.keyTextShadowColor", "按键文字阴影颜色" },
                { "kv.keyTextShadowOffset", "按键文字阴影偏移" },
                { "kv.keyTextShadowSoftness", "按键文字阴影柔度" },
                { "kv.enableCountTextShadow", "开启计数文字阴影" },
                { "kv.countTextShadowColor", "计数文字阴影颜色" },
                { "kv.countTextShadowOffset", "计数文字阴影偏移" },
                { "kv.countTextShadowSoftness", "计数文字阴影柔度" },
                { "kv.bulkSize", "批量修改当前配置按键大小" },
                { "kv.bulkWidth", "配置宽度设定" },
                { "kv.bulkHeight", "配置高度设定" },
                { "kv.applySizeToAllKeys", "应用大小到当前配置的所有按键" },
                { "kv.colorSettings", "颜色设置" },
                { "kv.background", "背景" },
                { "kv.border", "边框" },
                { "kv.text", "文本" },
                { "kv.bottomStatsText", "底部统计文本" },
                { "kv.normal", "未按下" },
                { "kv.pressed", "触发" },
                { "kv.kpsColor", "KPS 颜色" },
                { "kv.totalColor", "Total 颜色" },
                { "kv.keyPressAnimation", "按键动画" },
                { "kv.enableKeyPressAnimation", "开启按键动画" },
                { "kv.keyPressAnimationDuration", "动画时长" },
                { "kv.keyPressAnimationAffectColors", "颜色也使用动画过渡" },
                { "kv.keyPressAnimationScale", "按下缩放" },
                { "kv.keyPressAnimationOffsetX", "按下 X 偏移" },
                { "kv.keyPressAnimationOffsetY", "按下 Y 偏移" },
                { "kv.keyPressAnimationEasing", "缓动类型" },
                { "kv.keyRainSettings", "键雨 (Key Rain) 设置" },
                { "kv.enableKeyRain", "开启键雨" },
                { "kv.rainSpeed", "飞行速度" },
                { "kv.rainMaxHeight", "消失距离" },
                { "kv.rainRow1Offset", "第一排高度偏移" },
                { "kv.rainRow2Offset", "第二排高度偏移" },
                { "kv.rainFadeMode", "消失模式" },
                { "kv.rainFadeModeItems", "高度裁剪 (Clip)\0羽化透明 (Fade)\0" },
                { "kv.rainFadeHeight", "羽化高度" },
                { "kv.rainFadePower", "羽化程度" },
                { "kv.rainRow1WidthRatio", "第一排宽度比例" },
                { "kv.rainRow2WidthRatio", "第二排宽度比例" },
                { "kv.rainCornerRadius", "雨滴圆角" },
                { "kv.rainColor", "雨滴颜色" },
                { "kv.rainRow1Color", "第一排颜色" },
                { "kv.rainRow2Color", "第二排颜色" },
                { "kv.rainGradient", "启用雨滴颜色渐变" },
                { "kv.rainGradientMode", "雨滴渐变样式" },
                { "kv.rainGradientModeItems", "UV 渐变\0高度遮罩渐变\0" },
                { "kv.rainGradientHeight", "渐变高度" },
                { "kv.rainGradientPower", "渐变程度" },
                { "kv.rainGradientEndColor", "雨滴渐变结束色" },
                { "kv.rainRow1GradientEndColor", "第一排结束色" },
                { "kv.rainRow2GradientEndColor", "第二排结束色" },
                { "kv.rainHorizontalGradient", "启用雨滴横向渐变" },
                { "kv.rainHorizontalGradientEndColor", "雨滴右侧颜色" },
                { "kv.rainRow1HorizontalEndColor", "第一排右侧色" },
                { "kv.rainRow2HorizontalEndColor", "第二排右侧色" },
                { "kv.gradientVertical", "纵向渐变" },
                { "kv.gradientHorizontal", "横向渐变" },
                { "kv.gradientVerticalEnd", "底部颜色" },
                { "kv.gradientHorizontalEnd", "右侧颜色" },
                { "kv.backgroundNormalGradient", "未按下背景渐变" },
                { "kv.backgroundPressedGradient", "触发背景渐变" },
                { "kv.borderNormalGradient", "未按下边框渐变" },
                { "kv.borderPressedGradient", "触发边框渐变" },
                { "kv.textNormalGradient", "未按下文字渐变" },
                { "kv.textPressedGradient", "触发文字渐变" },
                { "kv.enableRainShadow", "开启键雨阴影" },
                { "kv.shadowColor", "阴影颜色" },
                { "kv.shadowOffsetX", "阴影偏移 X" },
                { "kv.shadowOffsetY", "阴影偏移 Y" },
                { "kv.shadowSoftness", "阴影柔度" },
                { "kv.shadowStrength", "阴影强度" },
                { "help.title", "CheryTools 功能说明书" },
                { "help.intro", "这里汇总 CheryTools 的主要功能、配置入口和常见注意事项。" },
                { "help.quickStart", "快速开始" },
                { "help.quickStart.1", "顶部栏用于打开 Tools、KV、OV、设置和帮助窗口；窗口开启时对应按钮会高亮。" },
                { "help.quickStart.2", "Settings 中可以切换语言、调整 ImGui 面板缩放、导入导出总配置，并重置窗口位置。" },
                { "help.quickStart.3", "KV 与 OV 都支持独立导入导出分享包，外置字体、图片、视频会一起打包。" },
                { "help.quickStart.4", "大多数修改会立即生效；完成配置后可在设置中导出 .cyt，或在 KV/OV 面板导出 .ctkv/.ctov。" },
                { "help.general", "通用操作" },
                { "help.general.1", "鼠标悬停在输入框或滑块上时，可以直接滚轮或拖动调整数值。" },
                { "help.general.2", "按住 Ctrl 点击滑块或拖动条，可以切换为手动输入数值。" },
                { "help.general.3", "文本输入后按 Enter 或点击其它位置即可提交。" },
                { "help.general.4", "颜色方块可以打开颜色编辑器，Alpha 控制透明度。" },
                { "help.general.5", "如果窗口被拖出屏幕，可以在设置中选择对应窗口并重置到屏幕中央。" },
                { "help.tools", "Tools" },
                { "help.tools.1", "优化页提供防弹键：同一个按键在极短间隔内重复输入时，可忽略第二次输入。" },
                { "help.tools.2", "优化页还可以禁用自动播放空格暂停、禁用游玩时滚轮缩放，并配置独立按键限制。" },
                { "help.tools.3", "视觉页可以隐藏判定文字，并调整星球、球环、尾巴等游玩视觉元素。" },
                { "help.tools.4", "游戏 UI 页只影响关卡游玩中的 UI，例如倒计时、准度条和关卡名称。" },
                { "help.tools.5", "部分游戏 UI 的位置、缩放和透明度属于高级控制，需要在设置中输入开发者 Key 解锁。" },
                { "help.tools.6", "Tools 功能尽量保持关闭即无额外消耗；遇到异常时可先逐项关闭排查。" },
                { "help.kv", "KV" },
                { "help.kv.1", "KV 支持多个配置，每个配置都可以单独启用；启用多个配置时会同时显示。" },
                { "help.kv.2", "新建配置可以从预设开始，也可以创建空白配置；旧版 KV 可通过迁移入口追加导入。" },
                { "help.kv.3", "综合设置控制整体位置、缩放、字体、按键限制和导入导出。" },
                { "help.kv.4", "按键设置控制背景、边框、文字、描边、阴影、圆角、深度和图片/视频按键。" },
                { "help.kv.5", "雨滴设置控制键雨启用、速度、高度、圆角、阴影、羽化和纵横渐变。" },
                { "help.kv.6", "动画设置控制按下/松开时的缩放、位移、颜色过渡和缓动。" },
                { "help.kv.7", "KV 视频按键最多启用一个，仅支持 .mp4，并可设置循环、透明度和内容缩放。" },
                { "help.kv.8", "导出的 .ctkv 会包含 KV 配置和使用到的外置资源，适合分享给其它玩家。" },
                { "help.freemake", "FreeMake 编辑器" },
                { "help.freemake.1", "左键单击选择按键，Ctrl + 左键可以多选。" },
                { "help.freemake.2", "双击重叠按键会在重叠按键之间轮换选择。" },
                { "help.freemake.3", "拖动按键可以移动；多选后拖动任意已选按键会整体移动。" },
                { "help.freemake.4", "鼠标中键拖动画布，滚轮缩放画布。" },
                { "help.freemake.5", "按键绑定可以点击后直接按下目标按键，不需要手动输入 KeyCode。" },
                { "help.freemake.6", "编辑器侧栏会按模式显示可用设置；文本模式、图片/视频模式和普通按键模式的选项不同。" },
                { "help.freemake.7", "单个或多个按键可以启用独立颜色、渐变、键雨和动画设置。" },
                { "help.ov", "OV" },
                { "help.ov.1", "OV 支持文本、图片、视频和进度条模块；同类模块之间可用深度控制遮挡顺序。" },
                { "help.ov.2", "文本模块支持 Tag、富文本颜色/字号、描边、阴影、语法高亮编辑器和右侧实时预览。" },
                { "help.ov.3", "Tag 插入窗口支持搜索；例如 {fps}、{progress:2}、{bpm:2}、{acc:2}、{wtime}。" },
                { "help.ov.4", "数字 Tag 支持 :位数 控制小数显示，并会自动去掉无意义的末尾 0。" },
                { "help.ov.5", "文本编辑器支持 #import regex 和 #regex /pattern/replacement/，用于对最终文本做正则替换。" },
                { "help.ov.6", "图片和视频模块可以设置位置、尺寸、旋转、锚点、透明度和对齐；OV 视频最多两个，仅支持 .mp4。" },
                { "help.ov.7", "进度条可以选择当前值、0% 值和 100% 值来源；适合做音乐播放、地图进度、准确率等条形显示。" },
                { "help.ov.8", "解锁 OV 拖动后，可以在游戏画面直接拖动模块，并使用吸附线辅助对齐。" },
                { "help.assets", "资源与分享" },
                { "help.assets.1", "导入外置字体、图片、视频时，资源会复制到游戏目录的 CheryToolsAssets 文件夹。" },
                { "help.assets.2", ".ctkv 只包含 KV 配置和资源，.ctov 只包含 OV 配置和资源，.cyt 包含总配置和资源。" },
                { "help.assets.3", "导入他人预设时，会按导出者记录的分辨率自动缩放位置和尺寸。" },
                { "help.assets.4", "如果覆盖安装后新功能缺失，建议在 UMM 中先卸载旧版，再重新安装新版。" },
                { "help.performance", "性能建议" },
                { "help.performance.1", "KV/OV 渲染会按刷新率和缓存状态尽量减少无效更新；空闲时避免额外重建。" },
                { "help.performance.2", "图片渲染倍率会影响显存和清晰度；更改后图片缓存会自动刷新。" },
                { "help.performance.3", "视频、柔化阴影、复杂渐变和大量模块会增加开销；不用时关闭即可避免对应成本。" },
                { "help.performance.4", "如果需要做性能对比，请保持同一谱面、同一刷新率、同一 KV/OV 配置和同一游戏状态。" },
                { "help.troubleshooting", "常见问题" },
                { "help.troubleshooting.1", "语言文件位于 Mod 目录的 Languages 文件夹；可以在设置中生成模板后手动编辑 JSON。" },
                { "help.troubleshooting.2", "自定义字体或图片不显示时，先确认资源文件仍在 CheryToolsAssets 中，路径也没有被移动或删除。" },
                { "help.troubleshooting.3", "视频偶发暂停时，确认文件是 .mp4，并尝试减少同时启用的视频模块数量。" },
                { "help.troubleshooting.4", "如果导入配置后显示异常，先确认导出者和导入者使用的是同一版本安装包。" },
                { "help.sponsors", "赞助者 / 鸣谢" },
                { "help.sponsors.intro", "感谢以下朋友对 CheryTools 开发的支持。" },
                { "help.sponsors.openBilibili", "打开 Bilibili" },
                { "settings.gameUiAdvancedUnlocked", "Game UI 高级控制已解锁" },
                { "settings.relock", "重新锁定" },
                { "settings.gameUiDevKey", "输入 Key" },
                { "settings.verify", "验证" },
                { "settings.gameUiDevHint", "用于解锁判定模式/不会失败/自动演奏的位置、缩放和透明度控制。" },
                { "settings.keyVerifyFailed", "Key 验证失败" },
                { "settings.exportCyt", "导出配置 (.cyt)" },
                { "settings.importCyt", "导入配置 (.cyt)" },
                { "settings.importXml", "导入配置 (XML)" },
                { "settings.configSavedInGameRoot", "配置已保存在游戏根目录!" },
                { "settings.legacyKvMigration", "旧 KV 配置迁移" },
                { "settings.legacyKvMigrationHint", "追加导入旧 16K/12K/10K/8K 为新 KV 配置，不覆盖当前配置。" },
                { "settings.importLegacyFromCurrent", "从当前 Settings.xml 导入旧 KV" },
                { "settings.importLegacyFromXml", "从备份 XML 导入旧 KV" },
                { "settings.importLegacyFromCyt", "从备份 .cyt 导入旧 KV" },
                { "settings.closeMenu", "关闭菜单" },
                { "freemake.title", "FreeMake Editor" },
                { "freemake.noSelectedConfig", "没有选中的 KV 配置" },
                { "freemake.mode.keys", "按键模式" },
                { "freemake.mode.text", "文本模式" },
                { "freemake.mode.imageVideo", "图片/视频模式" },
                { "freemake.selectAll", "全选" },
                { "freemake.clearSelection", "取消选择" },
                { "freemake.addNode", "添加新节点" },
                { "freemake.deleteSelected", "删除选中节点" },
                { "freemake.properties", "属性面板" },
                { "freemake.noNodeSelected", "未选择节点" },
                { "freemake.selectedNodes", "已选择: {0} 个节点" },
                { "freemake.useConfigShadow", "当前使用此配置的阴影设置" },
                { "freemake.animationUsesConfig", "按键动画当前使用此 KV 配置的动画设置。" },
                { "freemake.unselectable", "不可选中 (在按键模式下锁定)" },
                { "freemake.batchImageUnsupported", "批量图片编辑暂不支持" },
                { "ov.enableSystem", "开启 Overlayer 系统" },
                { "ov.onlyShowPlaying", "仅游戏时显示" },
                { "ov.unlockDrag", "解锁拖动" },
                { "ov.export", "导出 OV 配置 (.ctov)" },
                { "ov.import", "导入 OV 配置 (.ctov)" },
                { "ov.tab.texts", "文本 (Texts)" },
                { "ov.tab.images", "图片 (Images)" },
                { "ov.tab.videos", "视频" },
                { "ov.tab.progressBars", "进度条" },
                { "ov.newText", "新建文本 (+)" },
                { "ov.newImage", "新建图片 (+)" },
                { "ov.newVideo", "新建视频 (+)" },
                { "ov.newProgressBar", "新建进度条 (+)" },
                { "ov.maxVideos", "最多 2 个视频模块" },
                { "settings.title", "设置" },
                { "settings.hotkey", "呼出设置快捷键:" },
                { "settings.waitingKey", "[等待按键输入...]" },
                { "settings.localization", "语言设置" },
                { "settings.language", "界面语言" },
                { "settings.createLanguageConfigs", "新建/补齐语言配置 JSON" },
                { "settings.reloadLanguageConfigs", "重新加载语言配置" },
                { "settings.languageConfigHint", "语言文件位于 {0}，用户可以直接编辑对应 JSON。" },
                { "settings.languageConfigCreated", "语言配置已创建: {0}" },
                { "settings.languageConfigReloaded", "语言配置已重新加载" },
                { "settings.update", "更新" },
                { "settings.currentVersion", "当前版本: {0}" },
                { "settings.checkUpdate", "检查更新" },
                { "settings.updateAvailable", "发现新版本: {0}" },
                { "settings.updatePackage", "更新包: {0}" },
                { "settings.updateNotes", "更新说明" },
                { "settings.downloadUpdate", "下载更新包" },
                { "settings.installAndRestart", "安装并重启" },
                { "settings.updateDownloaded", "已下载: {0}" },
                { "settings.cloudSync", "Steam 云存档" },
                { "settings.cloudSync.steamUnavailable", "Steam 不可用，云存档功能已禁用。请通过 Steam 启动游戏。" },
                { "settings.cloudSync.upload", "上传设置到 Steam 云端" },
                { "settings.cloudSync.uploadSuccess", "设置已上传至 Steam 云端。" },
                { "settings.cloudSync.uploadFailed", "上传失败，请查看日志。" },
                { "settings.cloudSync.download", "从 Steam 云端下载设置" },
                { "settings.cloudSync.downloadSuccess", "已从 Steam 云端下载设置。" },
                { "settings.cloudSync.downloadFailed", "下载失败，请查看日志。" },
                { "settings.cloudSync.noCloudFile", "云端暂无存档。" },
                { "settings.windowPosition", "窗口位置" },
                { "settings.noOpenWindows", "当前没有可重置的已打开窗口" },
                { "settings.resetWindow", "重置窗口" },
                { "settings.resetToCenter", "重置到屏幕中央" },
                { "settings.imguiScale", "ImGui 面板缩放" },
                { "settings.overlayRefreshRate", "覆盖层刷新率" },
                { "settings.imageRenderScale", "图片渲染倍率" },
                { "settings.integration", "联动设置" },
                { "settings.xperfectDetected", "XPerfect 已检测到" },
                { "settings.xperfectMissing", "XPerfect 未检测到或未启用" },
                { "settings.refreshDetection", "刷新检测" },
                { "settings.developerOptions", "开发者选项" },
                { "tag.searchLabel", "搜索并插入 Tag:" },
                { "tag.insert", "插入" },
                { "tag.{xperfect:xpp}", "XPerfect / XPurePerfect 数量" },
                { "tag.{xperfect:epp}", "XPerfect / Early PurePerfect 数量" },
                { "tag.{xperfect:lpp}", "XPerfect / Late PurePerfect 数量" }
            };

            languages["English"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "meta.displayName", "English" },
                { "top.tools", "Tools" },
                { "top.keyViewer", "KeyViewer" },
                { "top.overlayer", "Overlayer" },
                { "top.settings", "Settings" },
                { "top.help", "Help" },
                { "window.tools", "Tools" },
                { "window.keyViewer", "KeyViewer" },
                { "window.overlayer", "Overlayer" },
                { "window.help", "Help" },
                { "window.settings", "Settings" },
                { "window.kvEditor", "KV editor" },
                { "tools.tab.optimization", "Optimization" },
                { "tools.tab.visual", "Visual" },
                { "tools.tab.gameUi", "Game UI" },
                { "tools.optimization.title", "Optimization" },
                { "tools.disableAutoplaySpacePause", "Disable autoplay Space pause" },
                { "tools.disablePlayModeScrollZoom", "Disable scroll zoom while playing" },
                { "tools.antiBounceKeys", "Anti-bounce keys" },
                { "tools.antiBounceIntervalMs", "Anti-bounce interval (ms)" },
                { "tools.antiBounceKeysHelp", "Ignore the second press when the same key is pressed again within 50 ms." },
                { "tools.visual.title", "Visual" },
                { "tools.hideHitTextEnabled", "Enable hit text hiding" },
                { "tools.hideAllHitText", "Hide all hit text" },
                { "tools.showAllHitText", "Show all hit text" },
                { "tools.customPlanetColors", "Enable custom planet colors" },
                { "tools.planetColorSettings", "Planet color settings" },
                { "tools.firePlanet", "Fire planet" },
                { "tools.icePlanet", "Ice planet" },
                { "tools.greenPlanet", "Third planet" },
                { "tools.ring", "Ring" },
                { "tools.tail", "Tail" },
                { "tools.gameUi.title", "Game UI" },
                { "tools.gameUi.hint", "Only active on the level play screen; menus, level select, and the level editor UI are not controlled." },
                { "tools.gameUi.enable", "Enable Game UI control" },
                { "tools.gameUi.resetAll", "Reset all" },
                { "tools.gameUi.control", "Control" },
                { "tools.gameUi.visible", "Visible" },
                { "tools.gameUi.advancedLocked", "Developer options are locked: this item only supports hiding. Position, scale, and alpha controls are disabled." },
                { "tools.gameUi.positionX", "Position X" },
                { "tools.gameUi.positionY", "Position Y" },
                { "tools.gameUi.scale", "Scale" },
                { "tools.gameUi.alpha", "Alpha" },
                { "tools.gameUi.resetThis", "Reset this" },
                { "tools.gameUi.target.levelName", "Level name" },
                { "tools.gameUi.target.countdown", "Countdown" },
                { "tools.gameUi.target.hitErrorMeter", "Hit error meter" },
                { "tools.gameUi.target.difficultySwitch", "Judgement mode switch" },
                { "tools.gameUi.target.noFailSwitch", "No-fail mode switch" },
                { "tools.gameUi.target.autoplaySwitch", "Autoplay switch" },
                { "tools.gameUi.target.autoplayText", "Autoplay text" },
                { "tools.gameUi.target.buildWatermark", "Test build watermark" },
                { "tools.inputLimit.title", "Input limit" },
                { "tools.inputLimit.enable", "Enable independent input limit" },
                { "tools.inputLimit.help", "When enabled, only registered keys below are allowed. Up to 30 keys; menu hotkey, Esc, Ctrl, and F10 always pass through." },
                { "tools.inputLimit.add", "Add limited key" },
                { "tools.inputLimit.waiting", "[Waiting for key...]" },
                { "tools.inputLimit.clear", "Clear limited keys" },
                { "common.index", "Index" },
                { "common.key", "Key" },
                { "common.action", "Action" },
                { "common.delete", "Delete" },
                { "kv.enable", "Enable KeyViewer" },
                { "kv.onlyShowPlaying", "Show only while playing" },
                { "kv.limitInput", "Limit input" },
                { "kv.resetStats", "Reset stats" },
                { "kv.export", "Export KV config (.ctkv)" },
                { "kv.import", "Import KV config (.ctkv)" },
                { "kv.newConfig", "New config" },
                { "kv.blankConfig", "Blank config" },
                { "kv.from16kPreset", "Start from 16K preset" },
                { "kv.from12kPreset", "Start from 12K preset" },
                { "kv.from10kPreset", "Start from 10K preset" },
                { "kv.from8kPreset", "Start from 8K preset" },
                { "kv.noConfig", "No KV config yet" },
                { "kv.createHint", "Click \"New config\" on the left to start." },
                { "kv.currentConfig", "Current config" },
                { "kv.name", "Name" },
                { "kv.configEnable", "Enable display" },
                { "kv.showInGame", "Show in game" },
                { "kv.nodeCount", "Node count: {0}" },
                { "kv.openEditor", "Open FreeMake editor" },
                { "kv.clearNodes", "Clear nodes" },
                { "kv.copyConfig", "Copy config" },
                { "kv.deleteConfig", "Delete config" },
                { "kv.replaceWithPreset", "Replace current config with preset:" },
                { "kv.emptyPreset", "Blank" },
                { "kv.appearanceSettings", "Current config appearance" },
                { "kv.section.general", "General" },
                { "kv.section.key", "Key settings" },
                { "kv.section.rain", "Rain settings" },
                { "kv.section.animation", "Animation settings" },
                { "kv.customFontPath", "Custom font path (e.g. D:/font.ttf or .otf)" },
                { "kv.keyTextOffsetX", "Config key text X offset" },
                { "kv.keyTextOffsetY", "Config key text Y offset" },
                { "kv.countTextOffsetX", "Config count text X offset" },
                { "kv.countTextOffsetY", "Config count text Y offset" },
                { "kv.reloadFont", "Reload font" },
                { "kv.scale", "Scale" },
                { "kv.hideCountText", "Hide count number" },
                { "kv.defaultBorderThickness", "Default border thickness" },
                { "kv.textOutline", "Text outline" },
                { "kv.enableKeyTextOutline", "Enable key text outline" },
                { "kv.keyTextOutlineColor", "Key text outline color" },
                { "kv.keyTextOutlineThickness", "Key text outline thickness" },
                { "kv.enableCountTextOutline", "Enable count text outline" },
                { "kv.countTextOutlineColor", "Count text outline color" },
                { "kv.countTextOutlineThickness", "Count text outline thickness" },
                { "kv.textShadow", "Text shadow" },
                { "kv.enableKeyTextShadow", "Enable key text shadow" },
                { "kv.keyTextShadowColor", "Key text shadow color" },
                { "kv.keyTextShadowOffset", "Key text shadow offset" },
                { "kv.keyTextShadowSoftness", "Key text shadow softness" },
                { "kv.enableCountTextShadow", "Enable count text shadow" },
                { "kv.countTextShadowColor", "Count text shadow color" },
                { "kv.countTextShadowOffset", "Count text shadow offset" },
                { "kv.countTextShadowSoftness", "Count text shadow softness" },
                { "kv.bulkSize", "Batch edit key size for current config" },
                { "kv.bulkWidth", "Config width" },
                { "kv.bulkHeight", "Config height" },
                { "kv.applySizeToAllKeys", "Apply size to all keys in current config" },
                { "kv.colorSettings", "Color settings" },
                { "kv.background", "Background" },
                { "kv.border", "Border" },
                { "kv.text", "Text" },
                { "kv.bottomStatsText", "Bottom stats text" },
                { "kv.normal", "Normal" },
                { "kv.pressed", "Pressed" },
                { "kv.kpsColor", "KPS color" },
                { "kv.totalColor", "Total color" },
                { "kv.keyPressAnimation", "Key press animation" },
                { "kv.enableKeyPressAnimation", "Enable key press animation" },
                { "kv.keyPressAnimationDuration", "Animation duration" },
                { "kv.keyPressAnimationAffectColors", "Animate color transition" },
                { "kv.keyPressAnimationScale", "Pressed scale" },
                { "kv.keyPressAnimationOffsetX", "Pressed X offset" },
                { "kv.keyPressAnimationOffsetY", "Pressed Y offset" },
                { "kv.keyPressAnimationEasing", "Easing" },
                { "kv.keyRainSettings", "Key Rain settings" },
                { "kv.enableKeyRain", "Enable Key Rain" },
                { "kv.rainSpeed", "Flight speed" },
                { "kv.rainMaxHeight", "Disappear distance" },
                { "kv.rainRow1Offset", "Row 1 height offset" },
                { "kv.rainRow2Offset", "Row 2 height offset" },
                { "kv.rainFadeMode", "Fade mode" },
                { "kv.rainFadeModeItems", "Height clip (Clip)\0Feathered fade (Fade)\0" },
                { "kv.rainFadeHeight", "Feather height" },
                { "kv.rainFadePower", "Feather power" },
                { "kv.rainRow1WidthRatio", "Row 1 width ratio" },
                { "kv.rainRow2WidthRatio", "Row 2 width ratio" },
                { "kv.rainCornerRadius", "Raindrop corner radius" },
                { "kv.rainColor", "Raindrop color" },
                { "kv.rainRow1Color", "Row 1 color" },
                { "kv.rainRow2Color", "Row 2 color" },
                { "kv.rainGradient", "Enable raindrop color gradient" },
                { "kv.rainGradientMode", "Raindrop gradient style" },
                { "kv.rainGradientModeItems", "UV gradient\0Height mask gradient\0" },
                { "kv.rainGradientHeight", "Gradient height" },
                { "kv.rainGradientPower", "Gradient power" },
                { "kv.rainGradientEndColor", "Raindrop gradient end color" },
                { "kv.rainRow1GradientEndColor", "Row 1 end color" },
                { "kv.rainRow2GradientEndColor", "Row 2 end color" },
                { "kv.rainHorizontalGradient", "Enable horizontal raindrop gradient" },
                { "kv.rainHorizontalGradientEndColor", "Raindrop right-side color" },
                { "kv.rainRow1HorizontalEndColor", "Row 1 right color" },
                { "kv.rainRow2HorizontalEndColor", "Row 2 right color" },
                { "kv.gradientVertical", "Vertical gradient" },
                { "kv.gradientHorizontal", "Horizontal gradient" },
                { "kv.gradientVerticalEnd", "Bottom color" },
                { "kv.gradientHorizontalEnd", "Right-side color" },
                { "kv.backgroundNormalGradient", "Normal background gradient" },
                { "kv.backgroundPressedGradient", "Pressed background gradient" },
                { "kv.borderNormalGradient", "Normal border gradient" },
                { "kv.borderPressedGradient", "Pressed border gradient" },
                { "kv.textNormalGradient", "Normal text gradient" },
                { "kv.textPressedGradient", "Pressed text gradient" },
                { "kv.enableRainShadow", "Enable Key Rain shadow" },
                { "kv.shadowColor", "Shadow color" },
                { "kv.shadowOffsetX", "Shadow offset X" },
                { "kv.shadowOffsetY", "Shadow offset Y" },
                { "kv.shadowSoftness", "Shadow softness" },
                { "kv.shadowStrength", "Shadow strength" },
                { "help.title", "CheryTools Manual" },
                { "help.intro", "A compact guide to CheryTools features, configuration entry points, and common notes." },
                { "help.quickStart", "Quick Start" },
                { "help.quickStart.1", "Use the top bar to open Tools, KV, OV, Settings, and Help. Buttons are highlighted while their windows are open." },
                { "help.quickStart.2", "Settings lets you switch language, scale the ImGui panel, import/export global config, and reset window positions." },
                { "help.quickStart.3", "KV and OV can each import or export share packages. External fonts, images, and videos are packed with them." },
                { "help.quickStart.4", "Most changes apply immediately. Export .cyt from Settings, or export .ctkv/.ctov from the KV/OV panels when finished." },
                { "help.general", "General" },
                { "help.general.1", "Hover inputs or sliders, then use the mouse wheel or drag to adjust values." },
                { "help.general.2", "Hold Ctrl and click a slider or drag control to enter values manually." },
                { "help.general.3", "Press Enter or click elsewhere to apply text input." },
                { "help.general.4", "Color swatches open the color editor; Alpha controls transparency." },
                { "help.general.5", "If a window is dragged outside the screen, select it in Settings and reset it to the center." },
                { "help.tools", "Tools" },
                { "help.tools.1", "Optimization includes anti-bounce keys: repeated input from the same key within a very short interval can be ignored." },
                { "help.tools.2", "Optimization can also disable autoplay Space pause, disable mouse-wheel zoom while playing, and configure independent key limits." },
                { "help.tools.3", "Visual options can hide judgement text and adjust planets, rings, tails, and other gameplay visuals." },
                { "help.tools.4", "Game UI only affects UI shown during level play, such as countdown, accuracy bar, and level title." },
                { "help.tools.5", "Some Game UI position, scale, and alpha controls are advanced options and require the developer key in Settings." },
                { "help.tools.6", "Tools features are designed to have no extra cost while disabled. If something behaves oddly, disable them one by one to isolate it." },
                { "help.kv", "KV" },
                { "help.kv.1", "KV supports multiple configs. Each config can be enabled independently, and multiple enabled configs render together." },
                { "help.kv.2", "New configs can start from a preset or from blank. Legacy KV configs can be appended through the migration entry." },
                { "help.kv.3", "General settings control global position, scale, font, key limits, and import/export." },
                { "help.kv.4", "Key settings control background, border, text, outline, shadow, corner radius, depth, and image/video keys." },
                { "help.kv.5", "Key Rain settings control enable state, speed, height, corner radius, shadow, feathering, and vertical/horizontal gradients." },
                { "help.kv.6", "Animation settings control press/release scale, offset, color transition, and easing." },
                { "help.kv.7", "KV supports at most one video key, .mp4 only, with loop, opacity, and content scale options." },
                { "help.kv.8", "Exported .ctkv packages include the KV config and referenced external assets, making them suitable for sharing." },
                { "help.freemake", "FreeMake editor" },
                { "help.freemake.1", "Left click to select a key; Ctrl + left click selects multiple keys." },
                { "help.freemake.2", "Double-click overlapping keys to cycle through them." },
                { "help.freemake.3", "Drag a key to move it; dragging any selected key moves the whole selection." },
                { "help.freemake.4", "Middle-drag pans the canvas, and the mouse wheel zooms it." },
                { "help.freemake.5", "For key binding, click the capture control and press the target key instead of typing a KeyCode manually." },
                { "help.freemake.6", "The editor sidebar only shows options available for the current mode. Text, image/video, and normal key modes differ." },
                { "help.freemake.7", "One or more selected keys can use independent color, gradient, Key Rain, and animation settings." },
                { "help.ov", "OV" },
                { "help.ov.1", "OV supports text, image, video, and progress bar modules. Depth controls draw order among modules of the same type." },
                { "help.ov.2", "Text modules support Tags, rich text color/size, outline, shadow, syntax-highlight editing, and a live preview pane." },
                { "help.ov.3", "The Tag insert window supports search. Examples: {fps}, {progress:2}, {bpm:2}, {acc:2}, {wtime}." },
                { "help.ov.4", "Numeric Tags support :digits precision and automatically remove unnecessary trailing zeroes." },
                { "help.ov.5", "The text editor supports #import regex and #regex /pattern/replacement/ for regex replacement on final text." },
                { "help.ov.6", "Image and video modules support position, size, rotation, pivot, opacity, and alignment. OV videos are limited to two, .mp4 only." },
                { "help.ov.7", "Progress bars can choose value, 0% value, and 100% value sources, useful for music time, map progress, accuracy, and similar displays." },
                { "help.ov.8", "After unlocking OV dragging, modules can be moved directly on the game screen with snap guide lines." },
                { "help.assets", "Assets and Sharing" },
                { "help.assets.1", "Imported external fonts, images, and videos are copied to the CheryToolsAssets folder in the game directory." },
                { "help.assets.2", ".ctkv contains only KV config and assets, .ctov contains only OV config and assets, and .cyt contains global config and assets." },
                { "help.assets.3", "When importing someone else's preset, position and size are scaled using the resolution recorded during export." },
                { "help.assets.4", "If new features are missing after overwriting an install, uninstall the old mod in UMM first, then install the new package." },
                { "help.performance", "Performance Tips" },
                { "help.performance.1", "KV/OV rendering reduces unnecessary updates through refresh-rate and cache checks, avoiding rebuilds while idle." },
                { "help.performance.2", "Image render scale affects VRAM use and sharpness. Changing it refreshes the image cache automatically." },
                { "help.performance.3", "Video, soft shadows, complex gradients, and many modules add cost. Disable unused features to avoid their cost." },
                { "help.performance.4", "For performance comparisons, keep the same level, refresh rate, KV/OV config, and game state." },
                { "help.troubleshooting", "Troubleshooting" },
                { "help.troubleshooting.1", "Language files are in the Languages folder under the mod directory. Generate templates in Settings, then edit the JSON files manually." },
                { "help.troubleshooting.2", "If custom fonts or images disappear, confirm the files still exist in CheryToolsAssets and the paths were not moved or deleted." },
                { "help.troubleshooting.3", "If video playback pauses unexpectedly, confirm the file is .mp4 and reduce the number of active video modules." },
                { "help.troubleshooting.4", "If an imported config displays incorrectly, confirm both exporter and importer use the same package version." },
                { "help.sponsors", "Sponsors / Credits" },
                { "help.sponsors.intro", "Thanks to the following friends for supporting CheryTools development." },
                { "help.sponsors.openBilibili", "Open Bilibili" },
                { "settings.gameUiAdvancedUnlocked", "Game UI advanced control unlocked" },
                { "settings.relock", "Relock" },
                { "settings.gameUiDevKey", "Enter key" },
                { "settings.verify", "Verify" },
                { "settings.gameUiDevHint", "Unlocks position, scale, and alpha controls for judgement mode, no-fail, and autoplay UI." },
                { "settings.keyVerifyFailed", "Key verification failed" },
                { "settings.exportCyt", "Export config (.cyt)" },
                { "settings.importCyt", "Import config (.cyt)" },
                { "settings.importXml", "Import config (XML)" },
                { "settings.configSavedInGameRoot", "Config saved in the game root!" },
                { "settings.legacyKvMigration", "Legacy KV migration" },
                { "settings.legacyKvMigrationHint", "Append legacy 16K/12K/10K/8K as new KV configs without overwriting current configs." },
                { "settings.importLegacyFromCurrent", "Import legacy KV from current Settings.xml" },
                { "settings.importLegacyFromXml", "Import legacy KV from backup XML" },
                { "settings.importLegacyFromCyt", "Import legacy KV from backup .cyt" },
                { "settings.closeMenu", "Close menu" },
                { "freemake.title", "FreeMake Editor" },
                { "freemake.noSelectedConfig", "No KV config selected" },
                { "freemake.mode.keys", "Key mode" },
                { "freemake.mode.text", "Text mode" },
                { "freemake.mode.imageVideo", "Image/video mode" },
                { "freemake.selectAll", "Select all" },
                { "freemake.clearSelection", "Clear selection" },
                { "freemake.addNode", "Add node" },
                { "freemake.deleteSelected", "Delete selected" },
                { "freemake.properties", "Properties" },
                { "freemake.noNodeSelected", "No node selected" },
                { "freemake.selectedNodes", "Selected: {0} node(s)" },
                { "freemake.useConfigShadow", "Currently using this config's shadow settings" },
                { "freemake.animationUsesConfig", "Key press animation currently uses this KV config's animation settings." },
                { "freemake.unselectable", "Unselectable (locked in key mode)" },
                { "freemake.batchImageUnsupported", "Batch image editing is not supported yet" },
                { "ov.enableSystem", "Enable Overlayer" },
                { "ov.onlyShowPlaying", "Show only while playing" },
                { "ov.unlockDrag", "Unlock dragging" },
                { "ov.export", "Export OV config (.ctov)" },
                { "ov.import", "Import OV config (.ctov)" },
                { "ov.tab.texts", "Texts" },
                { "ov.tab.images", "Images" },
                { "ov.tab.videos", "Videos" },
                { "ov.tab.progressBars", "Progress bars" },
                { "ov.newText", "New text (+)" },
                { "ov.newImage", "New image (+)" },
                { "ov.newVideo", "New video (+)" },
                { "ov.newProgressBar", "New progress bar (+)" },
                { "ov.maxVideos", "Up to 2 video modules" },
                { "settings.title", "Settings" },
                { "settings.hotkey", "Menu hotkey:" },
                { "settings.waitingKey", "[Press any key...]" },
                { "settings.localization", "Language" },
                { "settings.language", "Interface language" },
                { "settings.createLanguageConfigs", "Create/update language JSON" },
                { "settings.reloadLanguageConfigs", "Reload language JSON" },
                { "settings.languageConfigHint", "Language files are stored in {0}. Edit the matching JSON file to customize text." },
                { "settings.languageConfigCreated", "Language files created: {0}" },
                { "settings.languageConfigReloaded", "Language files reloaded" },
                { "settings.update", "Updates" },
                { "settings.currentVersion", "Current version: {0}" },
                { "settings.checkUpdate", "Check for updates" },
                { "settings.updateAvailable", "New version found: {0}" },
                { "settings.updatePackage", "Package: {0}" },
                { "settings.updateNotes", "Release notes" },
                { "settings.downloadUpdate", "Download update" },
                { "settings.installAndRestart", "Install and restart" },
                { "settings.updateDownloaded", "Downloaded: {0}" },
                { "settings.cloudSync", "Steam Cloud Save" },
                { "settings.cloudSync.steamUnavailable", "Steam unavailable. Cloud save disabled. Launch the game via Steam." },
                { "settings.cloudSync.upload", "Upload settings to Steam Cloud" },
                { "settings.cloudSync.uploadSuccess", "Settings uploaded to Steam Cloud." },
                { "settings.cloudSync.uploadFailed", "Upload failed. Check the log." },
                { "settings.cloudSync.download", "Download settings from Steam Cloud" },
                { "settings.cloudSync.downloadSuccess", "Settings downloaded from Steam Cloud." },
                { "settings.cloudSync.downloadFailed", "Download failed. Check the log." },
                { "settings.cloudSync.noCloudFile", "No cloud save found." },
                { "settings.windowPosition", "Window positions" },
                { "settings.noOpenWindows", "No open windows can be reset" },
                { "settings.resetWindow", "Reset window" },
                { "settings.resetToCenter", "Reset to screen center" },
                { "settings.imguiScale", "ImGui panel scale" },
                { "settings.overlayRefreshRate", "Overlay refresh rate" },
                { "settings.imageRenderScale", "Image render scale" },
                { "settings.integration", "Integrations" },
                { "settings.xperfectDetected", "XPerfect detected" },
                { "settings.xperfectMissing", "XPerfect was not detected or is not enabled" },
                { "settings.refreshDetection", "Refresh" },
                { "settings.developerOptions", "Developer options" },
                { "tag.searchLabel", "Search and insert tag:" },
                { "tag.insert", "Insert" },
                { "tag.{xperfect:xpp}", "XPerfect / XPurePerfect count" },
                { "tag.{xperfect:epp}", "XPerfect / Early PurePerfect count" },
                { "tag.{xperfect:lpp}", "XPerfect / Late PurePerfect count" }
            };

            languages["Korean"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                { "meta.displayName", "Korean" },
                { "top.tools", "도구" },
                { "top.keyViewer", "키 뷰어" },
                { "top.overlayer", "오버레이" },
                { "top.settings", "설정" },
                { "top.help", "도움말" },
                { "window.tools", "도구" },
                { "window.keyViewer", "키 뷰어" },
                { "window.overlayer", "오버레이" },
                { "window.help", "도움말" },
                { "window.settings", "설정" },
                { "window.kvEditor", "KV 편집기" },
                { "tools.tab.optimization", "최적화" },
                { "tools.tab.visual", "비주얼" },
                { "tools.tab.gameUi", "게임 UI" },
                { "tools.optimization.title", "최적화 설정" },
                { "tools.disableAutoplaySpacePause", "자동 재생 Space 일시정지 비활성화" },
                { "tools.disablePlayModeScrollZoom", "플레이 중 휠 줌 비활성화" },
                { "tools.antiBounceKeys", "키 바운스 방지" },
                { "tools.antiBounceIntervalMs", "바운스 방지 간격 (ms)" },
                { "tools.antiBounceKeysHelp", "같은 키가 50ms 안에 다시 눌리면 두 번째 입력을 무시합니다." },
                { "tools.visual.title", "비주얼" },
                { "tools.hideHitTextEnabled", "판정 텍스트 숨김 사용" },
                { "tools.hideAllHitText", "모든 판정 텍스트 숨기기" },
                { "tools.showAllHitText", "모든 판정 텍스트 표시" },
                { "tools.customPlanetColors", "커스텀 행성 색상 사용" },
                { "tools.planetColorSettings", "행성 색상 설정" },
                { "tools.firePlanet", "불 행성" },
                { "tools.icePlanet", "얼음 행성" },
                { "tools.greenPlanet", "세 번째 행성" },
                { "tools.ring", "링" },
                { "tools.tail", "꼬리" },
                { "tools.gameUi.title", "게임 UI" },
                { "tools.gameUi.hint", "레벨 플레이 화면에서만 적용되며 메뉴, 레벨 선택, 레벨 편집기 UI는 제어하지 않습니다." },
                { "tools.gameUi.enable", "게임 UI 제어 사용" },
                { "tools.gameUi.resetAll", "모두 초기화" },
                { "tools.gameUi.control", "제어" },
                { "tools.gameUi.visible", "표시" },
                { "tools.gameUi.advancedLocked", "개발자 옵션이 잠겨 있습니다. 이 항목은 숨기기만 지원하며 위치/배율/투명도 제어는 비활성화됩니다." },
                { "tools.gameUi.positionX", "위치 X" },
                { "tools.gameUi.positionY", "위치 Y" },
                { "tools.gameUi.scale", "배율" },
                { "tools.gameUi.alpha", "투명도" },
                { "tools.gameUi.resetThis", "이 항목 초기화" },
                { "tools.gameUi.target.levelName", "레벨 이름" },
                { "tools.gameUi.target.countdown", "카운트다운" },
                { "tools.gameUi.target.hitErrorMeter", "정확도 바" },
                { "tools.gameUi.target.difficultySwitch", "판정 모드 전환" },
                { "tools.gameUi.target.noFailSwitch", "실패 없음 모드 스위치" },
                { "tools.gameUi.target.autoplaySwitch", "자동 연주 스위치" },
                { "tools.gameUi.target.autoplayText", "자동 재생 텍스트" },
                { "tools.gameUi.target.buildWatermark", "테스트 빌드 워터마크" },
                { "tools.inputLimit.title", "입력 제한" },
                { "tools.inputLimit.enable", "독립 입력 제한 사용" },
                { "tools.inputLimit.help", "사용하면 아래에 등록된 키만 허용합니다. 최대 30개이며 메뉴 단축키, Esc, Ctrl, F10은 항상 허용됩니다." },
                { "tools.inputLimit.add", "제한 키 추가" },
                { "tools.inputLimit.waiting", "[키 입력 대기...]" },
                { "tools.inputLimit.clear", "제한 키 지우기" },
                { "common.index", "번호" },
                { "common.key", "키" },
                { "common.action", "동작" },
                { "common.delete", "삭제" },
                { "kv.enable", "키 뷰어 사용" },
                { "kv.onlyShowPlaying", "플레이 중에만 표시" },
                { "kv.limitInput", "입력 제한" },
                { "kv.resetStats", "통계 초기화" },
                { "kv.export", "KV 설정 내보내기 (.ctkv)" },
                { "kv.import", "KV 설정 가져오기 (.ctkv)" },
                { "kv.newConfig", "새 설정" },
                { "kv.blankConfig", "빈 설정" },
                { "kv.from16kPreset", "16K 프리셋으로 시작" },
                { "kv.from12kPreset", "12K 프리셋으로 시작" },
                { "kv.from10kPreset", "10K 프리셋으로 시작" },
                { "kv.from8kPreset", "8K 프리셋으로 시작" },
                { "kv.noConfig", "KV 설정이 아직 없습니다" },
                { "kv.createHint", "왼쪽의 \"새 설정\"을 눌러 시작하세요." },
                { "kv.currentConfig", "현재 설정" },
                { "kv.name", "이름" },
                { "kv.configEnable", "표시 사용" },
                { "kv.showInGame", "게임 중 표시" },
                { "kv.nodeCount", "노드 수: {0}" },
                { "kv.openEditor", "FreeMake 편집기 열기" },
                { "kv.clearNodes", "노드 지우기" },
                { "kv.copyConfig", "설정 복사" },
                { "kv.deleteConfig", "설정 삭제" },
                { "kv.replaceWithPreset", "현재 설정을 프리셋으로 덮어쓰기:" },
                { "kv.emptyPreset", "빈 설정" },
                { "kv.appearanceSettings", "현재 설정 외형" },
                { "kv.section.general", "종합 설정" },
                { "kv.section.key", "키 설정" },
                { "kv.section.rain", "빗방울 설정" },
                { "kv.section.animation", "애니메이션 설정" },
                { "kv.customFontPath", "커스텀 폰트 경로 (예: D:/font.ttf 또는 .otf)" },
                { "kv.keyTextOffsetX", "설정 키 텍스트 X 오프셋" },
                { "kv.keyTextOffsetY", "설정 키 텍스트 Y 오프셋" },
                { "kv.countTextOffsetX", "설정 카운트 텍스트 X 오프셋" },
                { "kv.countTextOffsetY", "설정 카운트 텍스트 Y 오프셋" },
                { "kv.reloadFont", "폰트 다시 불러오기" },
                { "kv.scale", "배율" },
                { "kv.hideCountText", "카운트 숫자 숨기기" },
                { "kv.defaultBorderThickness", "기본 테두리 두께" },
                { "kv.textOutline", "텍스트 외곽선" },
                { "kv.enableKeyTextOutline", "키 텍스트 외곽선 사용" },
                { "kv.keyTextOutlineColor", "키 텍스트 외곽선 색상" },
                { "kv.keyTextOutlineThickness", "키 텍스트 외곽선 두께" },
                { "kv.enableCountTextOutline", "카운트 텍스트 외곽선 사용" },
                { "kv.countTextOutlineColor", "카운트 텍스트 외곽선 색상" },
                { "kv.countTextOutlineThickness", "카운트 텍스트 외곽선 두께" },
                { "kv.textShadow", "텍스트 그림자" },
                { "kv.enableKeyTextShadow", "키 텍스트 그림자 사용" },
                { "kv.keyTextShadowColor", "키 텍스트 그림자 색상" },
                { "kv.keyTextShadowOffset", "키 텍스트 그림자 오프셋" },
                { "kv.keyTextShadowSoftness", "키 텍스트 그림자 부드러움" },
                { "kv.enableCountTextShadow", "카운트 텍스트 그림자 사용" },
                { "kv.countTextShadowColor", "카운트 텍스트 그림자 색상" },
                { "kv.countTextShadowOffset", "카운트 텍스트 그림자 오프셋" },
                { "kv.countTextShadowSoftness", "카운트 텍스트 그림자 부드러움" },
                { "kv.bulkSize", "현재 설정의 키 크기 일괄 수정" },
                { "kv.bulkWidth", "설정 너비" },
                { "kv.bulkHeight", "설정 높이" },
                { "kv.applySizeToAllKeys", "현재 설정의 모든 키에 크기 적용" },
                { "kv.colorSettings", "색상 설정" },
                { "kv.background", "배경" },
                { "kv.border", "테두리" },
                { "kv.text", "텍스트" },
                { "kv.bottomStatsText", "하단 통계 텍스트" },
                { "kv.normal", "기본" },
                { "kv.pressed", "입력됨" },
                { "kv.kpsColor", "KPS 색상" },
                { "kv.totalColor", "Total 색상" },
                { "kv.keyPressAnimation", "키 입력 애니메이션" },
                { "kv.enableKeyPressAnimation", "키 입력 애니메이션 사용" },
                { "kv.keyPressAnimationDuration", "애니메이션 시간" },
                { "kv.keyPressAnimationAffectColors", "색상도 애니메이션으로 전환" },
                { "kv.keyPressAnimationScale", "입력 시 배율" },
                { "kv.keyPressAnimationOffsetX", "입력 시 X 오프셋" },
                { "kv.keyPressAnimationOffsetY", "입력 시 Y 오프셋" },
                { "kv.keyPressAnimationEasing", "이징" },
                { "kv.keyRainSettings", "키 레인 설정" },
                { "kv.enableKeyRain", "키 레인 사용" },
                { "kv.rainSpeed", "비행 속도" },
                { "kv.rainMaxHeight", "사라지는 거리" },
                { "kv.rainRow1Offset", "1행 높이 오프셋" },
                { "kv.rainRow2Offset", "2행 높이 오프셋" },
                { "kv.rainFadeMode", "사라짐 모드" },
                { "kv.rainFadeModeItems", "높이 클립 (Clip)\0부드러운 페이드 (Fade)\0" },
                { "kv.rainFadeHeight", "페이드 높이" },
                { "kv.rainFadePower", "페이드 강도" },
                { "kv.rainRow1WidthRatio", "1행 너비 비율" },
                { "kv.rainRow2WidthRatio", "2행 너비 비율" },
                { "kv.rainCornerRadius", "빗방울 모서리 반경" },
                { "kv.rainColor", "빗방울 색상" },
                { "kv.rainRow1Color", "1행 색상" },
                { "kv.rainRow2Color", "2행 색상" },
                { "kv.rainGradient", "빗방울 색상 그라데이션 사용" },
                { "kv.rainGradientMode", "빗방울 그라데이션 방식" },
                { "kv.rainGradientModeItems", "UV 그라데이션\0높이 마스크 그라데이션\0" },
                { "kv.rainGradientHeight", "그라데이션 높이" },
                { "kv.rainGradientPower", "그라데이션 강도" },
                { "kv.rainGradientEndColor", "빗방울 그라데이션 끝 색상" },
                { "kv.rainRow1GradientEndColor", "1행 끝 색상" },
                { "kv.rainRow2GradientEndColor", "2행 끝 색상" },
                { "kv.rainHorizontalGradient", "빗방울 가로 그라데이션 사용" },
                { "kv.rainHorizontalGradientEndColor", "빗방울 오른쪽 색상" },
                { "kv.rainRow1HorizontalEndColor", "1행 오른쪽 색상" },
                { "kv.rainRow2HorizontalEndColor", "2행 오른쪽 색상" },
                { "kv.gradientVertical", "세로 그라데이션" },
                { "kv.gradientHorizontal", "가로 그라데이션" },
                { "kv.gradientVerticalEnd", "아래쪽 색상" },
                { "kv.gradientHorizontalEnd", "오른쪽 색상" },
                { "kv.backgroundNormalGradient", "기본 배경 그라데이션" },
                { "kv.backgroundPressedGradient", "눌림 배경 그라데이션" },
                { "kv.borderNormalGradient", "기본 테두리 그라데이션" },
                { "kv.borderPressedGradient", "눌림 테두리 그라데이션" },
                { "kv.textNormalGradient", "기본 텍스트 그라데이션" },
                { "kv.textPressedGradient", "눌림 텍스트 그라데이션" },
                { "kv.enableRainShadow", "키 레인 그림자 사용" },
                { "kv.shadowColor", "그림자 색상" },
                { "kv.shadowOffsetX", "그림자 오프셋 X" },
                { "kv.shadowOffsetY", "그림자 오프셋 Y" },
                { "kv.shadowSoftness", "그림자 부드러움" },
                { "kv.shadowStrength", "그림자 강도" },
                { "help.title", "CheryTools 기능 설명서" },
                { "help.intro", "CheryTools의 주요 기능, 설정 위치, 자주 확인할 내용을 정리한 설명서입니다." },
                { "help.quickStart", "빠른 시작" },
                { "help.quickStart.1", "상단 바에서 Tools, KV, OV, 설정, 도움말 창을 열 수 있습니다. 열린 창의 버튼은 강조 표시됩니다." },
                { "help.quickStart.2", "Settings에서 언어, ImGui 패널 배율, 전체 설정 가져오기/내보내기, 창 위치 초기화를 사용할 수 있습니다." },
                { "help.quickStart.3", "KV와 OV는 각각 공유 패키지 가져오기/내보내기를 지원하며 외부 폰트, 이미지, 비디오도 함께 포함됩니다." },
                { "help.quickStart.4", "대부분의 변경은 즉시 적용됩니다. 완료 후 Settings에서 .cyt를, KV/OV 패널에서 .ctkv/.ctov를 내보낼 수 있습니다." },
                { "help.general", "일반 조작" },
                { "help.general.1", "입력칸이나 슬라이더에 마우스를 올리고 휠 또는 드래그로 값을 조정할 수 있습니다." },
                { "help.general.2", "Ctrl을 누른 채 슬라이더나 드래그 컨트롤을 클릭하면 값을 직접 입력할 수 있습니다." },
                { "help.general.3", "텍스트 입력 후 Enter를 누르거나 다른 곳을 클릭하면 적용됩니다." },
                { "help.general.4", "색상 칸은 색상 편집기를 열며, Alpha는 투명도를 제어합니다." },
                { "help.general.5", "창이 화면 밖으로 나가면 Settings에서 해당 창을 선택해 화면 중앙으로 초기화할 수 있습니다." },
                { "help.tools", "Tools" },
                { "help.tools.1", "최적화 페이지에는 안티 바운스 키가 있습니다. 같은 키가 매우 짧은 간격으로 반복 입력되면 두 번째 입력을 무시할 수 있습니다." },
                { "help.tools.2", "최적화 페이지에서는 자동 연주 Space 일시정지 비활성화, 플레이 중 휠 줌 비활성화, 독립 키 제한도 설정할 수 있습니다." },
                { "help.tools.3", "시각 페이지에서는 판정 텍스트를 숨기고 행성, 링, 꼬리 등 플레이 시각 요소를 조정할 수 있습니다." },
                { "help.tools.4", "Game UI 페이지는 카운트다운, 정확도 바, 레벨 제목처럼 플레이 중 표시되는 UI에만 적용됩니다." },
                { "help.tools.5", "일부 Game UI 위치, 배율, 투명도 제어는 고급 옵션이며 Settings에서 개발자 Key를 입력해야 합니다." },
                { "help.tools.6", "Tools 기능은 꺼져 있을 때 추가 비용이 없도록 설계되어 있습니다. 이상이 있으면 항목별로 끄며 확인하세요." },
                { "help.kv", "KV" },
                { "help.kv.1", "KV는 여러 설정을 지원합니다. 각 설정은 개별로 켤 수 있으며, 여러 설정을 동시에 표시할 수 있습니다." },
                { "help.kv.2", "새 설정은 프리셋 또는 빈 설정에서 시작할 수 있습니다. 이전 KV 설정은 마이그레이션 항목으로 추가 가져오기가 가능합니다." },
                { "help.kv.3", "종합 설정은 전체 위치, 배율, 폰트, 키 제한, 가져오기/내보내기를 제어합니다." },
                { "help.kv.4", "키 설정은 배경, 테두리, 텍스트, 외곽선, 그림자, 모서리 반경, 깊이, 이미지/비디오 키를 제어합니다." },
                { "help.kv.5", "키 레인 설정은 사용 여부, 속도, 높이, 모서리 반경, 그림자, 페더, 세로/가로 그라데이션을 제어합니다." },
                { "help.kv.6", "애니메이션 설정은 누름/해제 시 배율, 위치 오프셋, 색상 전환, 이징을 제어합니다." },
                { "help.kv.7", "KV 비디오 키는 최대 하나만 사용할 수 있고 .mp4만 지원하며 반복, 투명도, 콘텐츠 배율을 설정할 수 있습니다." },
                { "help.kv.8", "내보낸 .ctkv에는 KV 설정과 참조된 외부 리소스가 포함되어 공유에 적합합니다." },
                { "help.freemake", "FreeMake 편집기" },
                { "help.freemake.1", "왼쪽 클릭으로 키를 선택하고, Ctrl + 왼쪽 클릭으로 다중 선택합니다." },
                { "help.freemake.2", "겹친 키는 더블 클릭으로 순환 선택할 수 있습니다." },
                { "help.freemake.3", "키를 드래그해 이동합니다. 여러 키를 선택한 뒤 선택 키 하나를 드래그하면 함께 이동합니다." },
                { "help.freemake.4", "마우스 가운데 버튼 드래그로 캔버스를 이동하고, 휠로 확대/축소합니다." },
                { "help.freemake.5", "키 바인딩은 캡처 컨트롤을 클릭한 뒤 원하는 키를 누르면 되며 KeyCode를 직접 입력할 필요가 없습니다." },
                { "help.freemake.6", "편집기 사이드바는 현재 모드에서 사용할 수 있는 옵션만 표시합니다. 텍스트, 이미지/비디오, 일반 키 모드는 옵션이 다릅니다." },
                { "help.freemake.7", "하나 또는 여러 선택 키에 독립 색상, 그라데이션, 키 레인, 애니메이션 설정을 적용할 수 있습니다." },
                { "help.ov", "OV" },
                { "help.ov.1", "OV는 텍스트, 이미지, 비디오, 진행 바 모듈을 지원합니다. 같은 종류 모듈 사이의 표시 순서는 깊이로 제어합니다." },
                { "help.ov.2", "텍스트 모듈은 Tag, 리치 텍스트 색상/크기, 외곽선, 그림자, 구문 강조 편집기, 실시간 미리보기를 지원합니다." },
                { "help.ov.3", "Tag 삽입 창은 검색을 지원합니다. 예: {fps}, {progress:2}, {bpm:2}, {acc:2}, {wtime}." },
                { "help.ov.4", "숫자 Tag는 :자리수 정밀도를 지원하며 불필요한 끝자리 0은 자동으로 제거됩니다." },
                { "help.ov.5", "텍스트 편집기는 최종 텍스트 정규식 치환을 위해 #import regex 및 #regex /pattern/replacement/를 지원합니다." },
                { "help.ov.6", "이미지와 비디오 모듈은 위치, 크기, 회전, 피벗, 투명도, 정렬을 지원합니다. OV 비디오는 최대 두 개, .mp4만 지원합니다." },
                { "help.ov.7", "진행 바는 현재 값, 0% 값, 100% 값 소스를 선택할 수 있어 음악 시간, 맵 진행도, 정확도 등에 적합합니다." },
                { "help.ov.8", "OV 드래그 잠금을 해제하면 게임 화면에서 모듈을 직접 이동하고 스냅 가이드선을 사용할 수 있습니다." },
                { "help.assets", "리소스와 공유" },
                { "help.assets.1", "외부 폰트, 이미지, 비디오를 가져오면 게임 폴더의 CheryToolsAssets 폴더로 복사됩니다." },
                { "help.assets.2", ".ctkv는 KV 설정과 리소스만, .ctov는 OV 설정과 리소스만, .cyt는 전체 설정과 리소스를 포함합니다." },
                { "help.assets.3", "다른 사람이 만든 프리셋을 가져올 때는 내보낼 때 기록된 해상도를 기준으로 위치와 크기를 자동 조정합니다." },
                { "help.assets.4", "덮어쓰기 설치 후 새 기능이 보이지 않으면 UMM에서 이전 모드를 먼저 제거한 뒤 새 패키지를 설치하세요." },
                { "help.performance", "성능 팁" },
                { "help.performance.1", "KV/OV 렌더링은 새로고침 주기와 캐시 상태를 이용해 불필요한 업데이트와 유휴 상태 재빌드를 줄입니다." },
                { "help.performance.2", "이미지 렌더 배율은 VRAM 사용량과 선명도에 영향을 줍니다. 변경하면 이미지 캐시가 자동으로 새로고침됩니다." },
                { "help.performance.3", "비디오, 부드러운 그림자, 복잡한 그라데이션, 많은 모듈은 비용이 증가합니다. 사용하지 않는 기능은 끄세요." },
                { "help.performance.4", "성능을 비교할 때는 같은 레벨, 같은 새로고침률, 같은 KV/OV 설정, 같은 게임 상태를 유지하세요." },
                { "help.troubleshooting", "문제 해결" },
                { "help.troubleshooting.1", "언어 파일은 모드 폴더의 Languages 폴더에 있습니다. Settings에서 템플릿을 만든 뒤 JSON을 직접 편집할 수 있습니다." },
                { "help.troubleshooting.2", "사용자 폰트나 이미지가 보이지 않으면 파일이 CheryToolsAssets에 남아 있고 경로가 이동 또는 삭제되지 않았는지 확인하세요." },
                { "help.troubleshooting.3", "비디오가 가끔 멈추면 파일이 .mp4인지 확인하고 동시에 켠 비디오 모듈 수를 줄여 보세요." },
                { "help.troubleshooting.4", "가져온 설정 표시가 이상하면 내보낸 사람과 가져온 사람이 같은 패키지 버전을 사용하는지 확인하세요." },
                { "help.sponsors", "후원자 / 감사" },
                { "help.sponsors.intro", "CheryTools 개발을 지원해 주신 분들께 감사드립니다." },
                { "help.sponsors.openBilibili", "Bilibili 열기" },
                { "settings.gameUiAdvancedUnlocked", "Game UI 고급 제어 잠금 해제됨" },
                { "settings.relock", "다시 잠그기" },
                { "settings.gameUiDevKey", "Key 입력" },
                { "settings.verify", "확인" },
                { "settings.gameUiDevHint", "판정 모드/실패 없음/자동 연주의 위치, 배율, 투명도 제어를 잠금 해제합니다." },
                { "settings.keyVerifyFailed", "Key 확인 실패" },
                { "settings.exportCyt", "설정 내보내기 (.cyt)" },
                { "settings.importCyt", "설정 가져오기 (.cyt)" },
                { "settings.importXml", "설정 가져오기 (XML)" },
                { "settings.configSavedInGameRoot", "설정이 게임 루트에 저장되었습니다!" },
                { "settings.legacyKvMigration", "이전 KV 설정 마이그레이션" },
                { "settings.legacyKvMigrationHint", "이전 16K/12K/10K/8K를 새 KV 설정으로 추가하며 현재 설정은 덮어쓰지 않습니다." },
                { "settings.importLegacyFromCurrent", "현재 Settings.xml에서 이전 KV 가져오기" },
                { "settings.importLegacyFromXml", "백업 XML에서 이전 KV 가져오기" },
                { "settings.importLegacyFromCyt", "백업 .cyt에서 이전 KV 가져오기" },
                { "settings.closeMenu", "메뉴 닫기" },
                { "freemake.title", "FreeMake Editor" },
                { "freemake.noSelectedConfig", "선택된 KV 설정이 없습니다" },
                { "freemake.mode.keys", "키 모드" },
                { "freemake.mode.text", "텍스트 모드" },
                { "freemake.mode.imageVideo", "이미지/비디오 모드" },
                { "freemake.selectAll", "전체 선택" },
                { "freemake.clearSelection", "선택 해제" },
                { "freemake.addNode", "새 노드 추가" },
                { "freemake.deleteSelected", "선택 노드 삭제" },
                { "freemake.properties", "속성 패널" },
                { "freemake.noNodeSelected", "선택된 노드 없음" },
                { "freemake.selectedNodes", "선택됨: 노드 {0}개" },
                { "freemake.useConfigShadow", "현재 이 설정의 그림자 설정을 사용 중" },
                { "freemake.animationUsesConfig", "키 입력 애니메이션은 현재 이 KV 설정의 애니메이션 설정을 사용합니다." },
                { "freemake.unselectable", "선택 불가 (키 모드에서 잠금)" },
                { "freemake.batchImageUnsupported", "이미지 일괄 편집은 아직 지원하지 않습니다" },
                { "ov.enableSystem", "오버레이 사용" },
                { "ov.onlyShowPlaying", "플레이 중에만 표시" },
                { "ov.unlockDrag", "드래그 잠금 해제" },
                { "ov.export", "OV 설정 내보내기 (.ctov)" },
                { "ov.import", "OV 설정 가져오기 (.ctov)" },
                { "ov.tab.texts", "텍스트" },
                { "ov.tab.images", "이미지" },
                { "ov.tab.videos", "비디오" },
                { "ov.tab.progressBars", "진행 막대" },
                { "ov.newText", "새 텍스트 (+)" },
                { "ov.newImage", "새 이미지 (+)" },
                { "ov.newVideo", "새 비디오 (+)" },
                { "ov.newProgressBar", "새 진행 막대 (+)" },
                { "ov.maxVideos", "비디오 모듈은 최대 2개" },
                { "settings.title", "설정" },
                { "settings.hotkey", "메뉴 단축키:" },
                { "settings.waitingKey", "[키 입력 대기...]" },
                { "settings.localization", "언어 설정" },
                { "settings.language", "인터페이스 언어" },
                { "settings.createLanguageConfigs", "언어 JSON 생성/업데이트" },
                { "settings.reloadLanguageConfigs", "언어 JSON 다시 불러오기" },
                { "settings.languageConfigHint", "언어 파일 위치: {0}. 원하는 JSON 파일을 직접 수정할 수 있습니다." },
                { "settings.languageConfigCreated", "언어 파일 생성됨: {0}" },
                { "settings.languageConfigReloaded", "언어 파일을 다시 불러왔습니다" },
                { "settings.update", "업데이트" },
                { "settings.currentVersion", "현재 버전: {0}" },
                { "settings.checkUpdate", "업데이트 확인" },
                { "settings.updateAvailable", "새 버전 발견: {0}" },
                { "settings.updatePackage", "패키지: {0}" },
                { "settings.updateNotes", "릴리스 노트" },
                { "settings.downloadUpdate", "업데이트 다운로드" },
                { "settings.installAndRestart", "설치 후 재시작" },
                { "settings.updateDownloaded", "다운로드됨: {0}" },
                { "settings.cloudSync", "Steam 클라우드 저장" },
                { "settings.cloudSync.steamUnavailable", "Steam을 사용할 수 없습니다. Steam을 통해 게임을 실행하세요." },
                { "settings.cloudSync.upload", "Steam 클라우드에 설정 업로드" },
                { "settings.cloudSync.uploadSuccess", "Steam 클라우드에 설정이 업로드되었습니다." },
                { "settings.cloudSync.uploadFailed", "업로드 실패. 로그를 확인하세요." },
                { "settings.cloudSync.download", "Steam 클라우드에서 설정 다운로드" },
                { "settings.cloudSync.downloadSuccess", "Steam 클라우드에서 설정이 다운로드되었습니다." },
                { "settings.cloudSync.downloadFailed", "다운로드 실패. 로그를 확인하세요." },
                { "settings.cloudSync.noCloudFile", "클라우드에 저장된 파일이 없습니다." },
                { "settings.windowPosition", "창 위치" },
                { "settings.noOpenWindows", "현재 재설정할 수 있는 열린 창이 없습니다" },
                { "settings.resetWindow", "창 재설정" },
                { "settings.resetToCenter", "화면 중앙으로 재설정" },
                { "settings.imguiScale", "ImGui 패널 배율" },
                { "settings.overlayRefreshRate", "오버레이 새로고침 속도" },
                { "settings.imageRenderScale", "이미지 렌더 배율" },
                { "settings.integration", "연동 설정" },
                { "settings.xperfectDetected", "XPerfect 감지됨" },
                { "settings.xperfectMissing", "XPerfect를 감지하지 못했거나 비활성화됨" },
                { "settings.refreshDetection", "새로고침" },
                { "settings.developerOptions", "개발자 옵션" },
                { "tag.searchLabel", "Tag 검색 및 삽입:" },
                { "tag.insert", "삽입" },
                { "tag.{xperfect:xpp}", "XPerfect / XPurePerfect 수" },
                { "tag.{xperfect:epp}", "XPerfect / Early PurePerfect 수" },
                { "tag.{xperfect:lpp}", "XPerfect / Late PurePerfect 수" }
            };

            return languages;
        }
    }
}
