<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>CheryTools.Loaders.BepInEx</RootNamespace>
    <AssemblyName>CheryTools.Loader.BepInEx</AssemblyName>
    <Version>26.4.0</Version>
    <OutputPath>..\..\bin\Loaders\BepInEx\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GameExePath>D:\Steam\steamapps\common\A Dance of Fire and Ice\A Dance of Fire and Ice.exe</GameExePath>
    <GameDir>$([System.IO.Path]::GetDirectoryName($(GameExePath)))</GameDir>
    <GameFileName>$([System.IO.Path]::GetFileNameWithoutExtension($(GameExePath)))</GameFileName>
    <ManagedAssembliesDir>$(GameDir)\$(GameFileName)_Data\Managed</ManagedAssembliesDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CheryTools.csproj" />
    <PackageReference Include="BepInEx.Core" Version="5.4.21" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedAssembliesDir)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedAssembliesDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
