<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>CheryTools.Loaders.MelonLoader</RootNamespace>
    <AssemblyName>CheryTools.Loader.MelonLoader</AssemblyName>
    <Version>26.4.0</Version>
    <OutputPath>..\..\bin\Loaders\MelonLoader\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CheryTools.csproj" />
    <PackageReference Include="LavaGang.MelonLoader" Version="0.7.3" GeneratePathProperty="true">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MelonLoader">
      <HintPath>$(PkgLavaGang_MelonLoader)\lib\net472\MelonLoader.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
